### ISSUE TITLE
Frame size for `LengthDelimitedCodec` too small, when notarizing large traffic data

### ISSUE THREAD

**Issue by th4s** [tlsnotary/tlsn-utils#10]
When trying to notarize huge transcripts (e.g. ~150KB), the default frame length from `LengthDelimitedCodec` is too small with 8MB. This triggers the error `frame size too big`.

**Comment by sinui0** [comment]
This would imply a message >8MB being sent, which message was it?

**Comment by th4s** [comment]
I think it was related to OT data.

**Comment by sinui0** [comment]
This is most likely the matrix that the KOS receiver sends during extension. To address this we can chunk it up into batches. If we weren't planning on deprecating KOS I would also suggest to implement a streaming matrix transpose to go with this.

**Comment by sinui0** [comment]
Fixed. The solution to this is not to increase the max frame size, but to send smaller messages. This issue in TLSNotary is resolved in v0.1.0-alpha.4 which we're releasing today.
